name = "test-logv2"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true
build_base_image = "golang:1.19.1"
go_version = "1.19"
enable_go_build_cache = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "smallbrain"
instances = { min = 1, max = 200, default = 1 }